export const CURRENCY_MULTIPLIERS = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 152,
  SGD: 1.34,
  AUD: 1.52,
};

export const DATASET_DISCLAIMER =
  'Demo dataset: illustrative values bundled with this app, not verified against live airline GDS or hotel inventory.';

export const DESTINATION_KEYS = {
  tokyo: { city: 'Tokyo', code: 'TYO', country: 'Japan' },
  tyo: { city: 'Tokyo', code: 'TYO', country: 'Japan' },
  hnd: { city: 'Tokyo', code: 'TYO', country: 'Japan' },
  nrt: { city: 'Tokyo', code: 'TYO', country: 'Japan' },
  paris: { city: 'Paris', code: 'PAR', country: 'France' },
  par: { city: 'Paris', code: 'PAR', country: 'France' },
  cdg: { city: 'Paris', code: 'PAR', country: 'France' },
  rome: { city: 'Rome', code: 'ROM', country: 'Italy' },
  rom: { city: 'Rome', code: 'ROM', country: 'Italy' },
  fco: { city: 'Rome', code: 'ROM', country: 'Italy' },
  reykjavik: { city: 'Reykjavik', code: 'KEF', country: 'Iceland' },
  kef: { city: 'Reykjavik', code: 'KEF', country: 'Iceland' },
  iceland: { city: 'Reykjavik', code: 'KEF', country: 'Iceland' },
};

export function resolveDestination(input) {
  if (!input || typeof input !== 'string') return null;
  const cleaned = input.trim().toLowerCase();
  // Exact match first
  if (DESTINATION_KEYS[cleaned]) return DESTINATION_KEYS[cleaned];
  // Substring whole word check
  for (const [key, val] of Object.entries(DESTINATION_KEYS)) {
    const regex = new RegExp(`\\b${key}\\b`, 'i');
    if (regex.test(cleaned)) return val;
  }
  return null;
}

export const FLIGHTS_DATA = {
  TYO: [
    {
      id: 'fl-hnd-101',
      airline: 'All Nippon Airways (ANA)',
      airlineCode: 'NH',
      flightNumber: 'NH 109',
      origin: 'JFK',
      destination: 'HND',
      departureTime: '11:30 AM',
      arrivalTime: '03:15 PM (+1d)',
      duration: '14h 45m',
      stops: 'Nonstop',
      basePrice: 1120,
      cabinClass: 'Economy Standard',
      carbonKg: 490,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
    {
      id: 'fl-hnd-102',
      airline: 'Japan Airlines (JAL)',
      airlineCode: 'JL',
      flightNumber: 'JL 005',
      origin: 'JFK',
      destination: 'HND',
      departureTime: '01:45 PM',
      arrivalTime: '05:30 PM (+1d)',
      duration: '14h 45m',
      stops: 'Nonstop',
      basePrice: 1240,
      cabinClass: 'Premium Economy',
      carbonKg: 510,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
    {
      id: 'fl-hnd-103',
      airline: 'United Airlines',
      airlineCode: 'UA',
      flightNumber: 'UA 79',
      origin: 'JFK',
      destination: 'NRT',
      departureTime: '09:10 AM',
      arrivalTime: '01:55 PM (+1d)',
      duration: '15h 45m',
      stops: '1 Stop',
      stopCity: 'SFO (1h 35m)',
      basePrice: 890,
      cabinClass: 'Economy Saver',
      carbonKg: 535,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
  ],
  PAR: [
    {
      id: 'fl-cdg-201',
      airline: 'Air France',
      airlineCode: 'AF',
      flightNumber: 'AF 023',
      origin: 'JFK',
      destination: 'CDG',
      departureTime: '04:30 PM',
      arrivalTime: '06:05 AM (+1d)',
      duration: '7h 35m',
      stops: 'Nonstop',
      basePrice: 740,
      cabinClass: 'Economy Classic',
      carbonKg: 280,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
    {
      id: 'fl-cdg-202',
      airline: 'Delta Air Lines',
      airlineCode: 'DL',
      flightNumber: 'DL 264',
      origin: 'JFK',
      destination: 'CDG',
      departureTime: '07:20 PM',
      arrivalTime: '08:55 AM (+1d)',
      duration: '7h 35m',
      stops: 'Nonstop',
      basePrice: 810,
      cabinClass: 'Comfort+',
      carbonKg: 290,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
    {
      id: 'fl-cdg-203',
      airline: 'British Airways',
      airlineCode: 'BA',
      flightNumber: 'BA 178',
      origin: 'JFK',
      destination: 'CDG',
      departureTime: '08:00 AM',
      arrivalTime: '09:20 PM',
      duration: '8h 20m',
      stops: '1 Stop',
      stopCity: 'LHR (1h 15m)',
      basePrice: 590,
      cabinClass: 'Standard Economy',
      carbonKg: 310,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
  ],
  ROM: [
    {
      id: 'fl-fco-301',
      airline: 'ITA Airways',
      airlineCode: 'AZ',
      flightNumber: 'AZ 609',
      origin: 'JFK',
      destination: 'FCO',
      departureTime: '05:40 PM',
      arrivalTime: '08:15 AM (+1d)',
      duration: '8h 35m',
      stops: 'Nonstop',
      basePrice: 860,
      cabinClass: 'Classic Economy',
      carbonKg: 330,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
    {
      id: 'fl-fco-302',
      airline: 'Lufthansa',
      airlineCode: 'LH',
      flightNumber: 'LH 401',
      origin: 'JFK',
      destination: 'FCO',
      departureTime: '03:50 PM',
      arrivalTime: '08:40 AM (+1d)',
      duration: '9h 50m',
      stops: '1 Stop',
      stopCity: 'MUC (1h 20m)',
      basePrice: 680,
      cabinClass: 'Economy Smart',
      carbonKg: 345,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
  ],
  KEF: [
    {
      id: 'fl-kef-401',
      airline: 'Icelandair',
      airlineCode: 'FI',
      flightNumber: 'FI 614',
      origin: 'JFK',
      destination: 'KEF',
      departureTime: '08:30 PM',
      arrivalTime: '06:15 AM (+1d)',
      duration: '5h 45m',
      stops: 'Nonstop',
      basePrice: 620,
      cabinClass: 'Economy Standard',
      carbonKg: 210,
      baggageIncluded: true,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
    {
      id: 'fl-kef-402',
      airline: 'Play Airlines',
      airlineCode: 'OG',
      flightNumber: 'OG 112',
      origin: 'JFK',
      destination: 'KEF',
      departureTime: '06:15 PM',
      arrivalTime: '04:30 AM (+1d)',
      duration: '6h 15m',
      stops: 'Nonstop',
      basePrice: 430,
      cabinClass: 'Basic Economy',
      carbonKg: 225,
      baggageIncluded: false,
      mcpSource: 'WanderPulse Demo Flights Catalog',
    },
  ],
};

export const HOTELS_DATA = {
  Tokyo: [
    {
      id: 'ht-tko-01',
      name: 'The Capitol Hotel Tokyu',
      city: 'Tokyo',
      neighborhood: 'Chiyoda / Akasaka',
      rating: 4.8,
      reviews: 1420,
      basePricePerNight: 380,
      amenities: ['Direct Subway Access', 'Japanese Garden View', 'Spa & Onsen', 'Free Wi-Fi'],
      cancellation: 'Free cancellation up to 48 hours prior',
      badge: 'Staff Choice',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
    {
      id: 'ht-tko-02',
      name: 'Trunk Hotel Yoyogi Park',
      city: 'Tokyo',
      neighborhood: 'Shibuya / Harajuku',
      rating: 4.7,
      reviews: 890,
      basePricePerNight: 290,
      amenities: ['Rooftop Infinity Pool', 'Boutique Coffee Lounge', 'Curated Art Decor', 'Locally Sourced Dining'],
      cancellation: 'Free cancellation up to 7 days prior',
      badge: 'Design Boutique',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
    {
      id: 'ht-tko-03',
      name: 'Hotel Gracery Shinjuku',
      city: 'Tokyo',
      neighborhood: 'Kabukicho / Shinjuku',
      rating: 4.5,
      reviews: 3250,
      basePricePerNight: 165,
      amenities: ['Godzilla Terrace', '5 min from JR Shinjuku Station', 'Modern Minimalist', 'Concierge Service'],
      cancellation: 'Non-refundable discount rate available',
      badge: 'Best Value',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
  ],
  Paris: [
    {
      id: 'ht-par-01',
      name: 'Hôtel Madame Rêve',
      city: 'Paris',
      neighborhood: '1st Arrondissement (Louvre - Bourse)',
      rating: 4.8,
      reviews: 640,
      basePricePerNight: 440,
      amenities: ['Panoramic Sky Bar', 'Historic Post Office Revival', 'Signature Spa', 'Luxury Robes & Linens'],
      cancellation: 'Free cancellation up to 72 hours prior',
      badge: 'Luxury Historic',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
    {
      id: 'ht-par-02',
      name: 'The Hoxton, Paris',
      city: 'Paris',
      neighborhood: '2nd Arrondissement (Sentier)',
      rating: 4.6,
      reviews: 1820,
      basePricePerNight: 285,
      amenities: ['18th-century Courtyard', 'Rivié Brasserie', 'Speakeasy Cocktail Bar', 'Walk to Marais'],
      cancellation: 'Free cancellation up to 48 hours prior',
      badge: 'Social & Hip',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
  ],
  Rome: [
    {
      id: 'ht-rom-01',
      name: 'Singer Palace Hotel',
      city: 'Rome',
      neighborhood: 'Trevi / Pantheon',
      rating: 4.9,
      reviews: 790,
      basePricePerNight: 420,
      amenities: ['Rooftop Jim’s Bar', 'Steps to Pantheon & Trevi', 'Art Deco Architecture', 'Full Butler Service'],
      cancellation: 'Free cancellation up to 48 hours prior',
      badge: 'Exceptional Luxury',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
    {
      id: 'ht-rom-02',
      name: 'The Hoxton Rome',
      city: 'Rome',
      neighborhood: 'Parioli / Villa Borghese',
      rating: 4.6,
      reviews: 1150,
      basePricePerNight: 220,
      amenities: ['Mid-century Italian Design', 'Beverly Restaurant', 'Spacious Terrace', 'Boutique Coffee'],
      cancellation: 'Free cancellation up to 72 hours prior',
      badge: 'Boutique Relaxed',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
  ],
  Reykjavik: [
    {
      id: 'ht-kef-01',
      name: 'The Reykjavik EDITION',
      city: 'Reykjavik',
      neighborhood: 'Old Harbour / Harpa',
      rating: 4.8,
      reviews: 910,
      basePricePerNight: 490,
      amenities: ['Geothermal Spa with Hydrotherapy', 'Rooftop Northern Lights Lounge', 'Harbour Waterfront Views'],
      cancellation: 'Free cancellation up to 7 days prior',
      badge: 'Nordic Luxury',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
    {
      id: 'ht-kef-02',
      name: 'Exeter Hotel by Keahotels',
      city: 'Reykjavik',
      neighborhood: 'Old Harbour Quarter',
      rating: 4.6,
      reviews: 1430,
      basePricePerNight: 245,
      amenities: ['Nordic Sauna & Cold Plunge', 'Deig Bakery on-site', 'Industrial Contemporary', 'Port Access'],
      cancellation: 'Free cancellation up to 48 hours prior',
      badge: 'Harbour Chic',
      mcpSource: 'WanderPulse Demo Hotels Catalog',
    },
  ],
};

export const WEATHER_DATA = {
  Tokyo: [
    { day: 1, tempC: 21, tempF: 70, condition: 'Sunny & Crisp', rainChance: 10, isRainy: false },
    { day: 2, tempC: 19, tempF: 66, condition: 'Passing Showers', rainChance: 68, isRainy: true },
    { day: 3, tempC: 22, tempF: 72, condition: 'Clear Sky', rainChance: 15, isRainy: false },
    { day: 4, tempC: 20, tempF: 68, condition: 'Partly Cloudy', rainChance: 25, isRainy: false },
  ],
  Paris: [
    { day: 1, tempC: 18, tempF: 64, condition: 'Mild & Sunny', rainChance: 15, isRainy: false },
    { day: 2, tempC: 16, tempF: 61, condition: 'Intermittent Rain', rainChance: 78, isRainy: true },
    { day: 3, tempC: 17, tempF: 63, condition: 'Overcast with Drizzle', rainChance: 65, isRainy: true },
    { day: 4, tempC: 19, tempF: 66, condition: 'Sunny Breaks', rainChance: 20, isRainy: false },
  ],
  Rome: [
    { day: 1, tempC: 24, tempF: 75, condition: 'Warm & Sunny', rainChance: 5, isRainy: false },
    { day: 2, tempC: 23, tempF: 73, condition: 'Clear', rainChance: 10, isRainy: false },
    { day: 3, tempC: 20, tempF: 68, condition: 'Thunderstorms', rainChance: 82, isRainy: true },
    { day: 4, tempC: 22, tempF: 72, condition: 'Breezy & Fair', rainChance: 20, isRainy: false },
  ],
  Reykjavik: [
    { day: 1, tempC: 8, tempF: 46, condition: 'Cool & Clear (Aurora Alert)', rainChance: 12, isRainy: false },
    { day: 2, tempC: 6, tempF: 43, condition: 'Sleet & Gusts', rainChance: 85, isRainy: true },
    { day: 3, tempC: 7, tempF: 45, condition: 'Overcast & Crisp', rainChance: 30, isRainy: false },
    { day: 4, tempC: 9, tempF: 48, condition: 'Scattered Showers', rainChance: 55, isRainy: true },
  ],
};

export const ATTRACTIONS_DATA = {
  Tokyo: [
    {
      id: 'act-tko-01',
      title: 'Meiji Jingu Shrine & Yoyogi Forest Walk',
      category: 'Culture',
      location: 'Shibuya',
      durationHours: 2.5,
      cost: 0,
      isOutdoor: true,
      isAnchorEvent: true,
      weatherSuitability: 'Sunny Preferred',
      description: 'Stately Shinto shrine nestled in a serene 170-acre evergreen forest.',
      rainAlternative: {
        title: 'Mori Art Museum & Roppongi Hills Observation',
        category: 'Culture',
        location: 'Roppongi Hills Mori Tower 53F',
        description: 'World-renowned contemporary art with indoor 360-degree skyline views.',
        cost: 18,
      },
    },
    {
      id: 'act-tko-02',
      title: 'Shinjuku Gyoen National Garden Walking Tour',
      category: 'Nature',
      location: 'Shinjuku',
      durationHours: 2.0,
      cost: 5,
      isOutdoor: true,
      isAnchorEvent: false,
      weatherSuitability: 'Sunny Preferred',
      description: 'Expansive historic garden featuring traditional Japanese landscaping and greenhouses.',
      rainAlternative: {
        title: 'teamLab Borderless Digital Art Museum',
        category: 'Culture',
        location: 'Azabudai Hills',
        description: 'Spectacular covered immersive projection mapping and interactive digital installations.',
        cost: 28,
      },
    },
    {
      id: 'act-tko-03',
      title: 'Tsukiji Outer Market Culinary Tasting Crawl',
      category: 'Culinary',
      location: 'Chuo / Tsukiji',
      durationHours: 2.0,
      cost: 35,
      isOutdoor: false,
      isAnchorEvent: true,
      weatherSuitability: 'All-Weather',
      description: 'Lively covered market lanes offering fresh sashimi skewers, tamagoyaki, and matcha.',
    },
  ],
  Paris: [
    {
      id: 'act-par-01',
      title: 'Montmartre & Sacré-Cœur Hilltop Walking Exploration',
      category: 'Sightseeing',
      location: '18th Arrondissement',
      durationHours: 2.5,
      cost: 0,
      isOutdoor: true,
      isAnchorEvent: true,
      weatherSuitability: 'Sunny Preferred',
      description: 'Cobblestone artisan alleys leading up to the panoramic terrace of Sacré-Cœur.',
      rainAlternative: {
        title: 'Musée d’Orsay Impressionist Masterpieces Tour',
        category: 'Culture',
        location: 'Left Bank 7th Arr.',
        description: 'Covered Beaux-Arts former railway station exhibiting Monet, Renoir, and Van Gogh.',
        cost: 16,
      },
    },
    {
      id: 'act-par-02',
      title: 'Jardin du Luxembourg & Latin Quarter Bookstalls',
      category: 'Nature',
      location: '6th Arrondissement',
      durationHours: 2.0,
      cost: 0,
      isOutdoor: true,
      isAnchorEvent: false,
      weatherSuitability: 'Sunny Preferred',
      description: 'Tree-lined gravel promenades, Medici fountain, and historic bouquinistes along the Seine.',
      rainAlternative: {
        title: 'Historic Covered Passages Tour (Galerie Vivienne & Panoramas)',
        category: 'Culture',
        location: '2nd Arrondissement',
        description: 'Glass-roofed 19th-century mosaic arcades with antiquarian bookstores and tearooms.',
        cost: 0,
      },
    },
    {
      id: 'act-par-03',
      title: 'Seine River Sunset Architecture Cruise',
      category: 'Sightseeing',
      location: 'Pont Neuf',
      durationHours: 1.5,
      cost: 22,
      isOutdoor: false,
      isAnchorEvent: true,
      weatherSuitability: 'All-Weather',
      description: 'Gliding past Notre-Dame, the Louvre, and the Eiffel Tower under glowing evening lights.',
    },
  ],
  Rome: [
    {
      id: 'act-rom-01',
      title: 'Colosseum & Roman Forum Archaeological Arena Walk',
      category: 'Culture',
      location: 'Piazza del Colosseo',
      durationHours: 3.0,
      cost: 26,
      isOutdoor: true,
      isAnchorEvent: true,
      weatherSuitability: 'Sunny Preferred',
      description: 'Epic stroll through the gladiator arena floor and marble ruins of the Roman Empire.',
      rainAlternative: {
        title: 'Capitoline Museums & Underground Galleria Lapidaria',
        category: 'Culture',
        location: 'Piazza del Campidoglio',
        description: 'Ancient bronze and marble masterpieces in protected covered palazzi.',
        cost: 18,
      },
    },
    {
      id: 'act-rom-02',
      title: 'Villa Borghese Gardens & Rowboat Lake',
      category: 'Nature',
      location: 'Pincian Hill',
      durationHours: 2.0,
      cost: 6,
      isOutdoor: true,
      isAnchorEvent: false,
      weatherSuitability: 'Sunny Preferred',
      description: 'Lush English-style landscaped park with panoramic sunset terrace over Piazza del Popolo.',
      rainAlternative: {
        title: 'Galleria Borghese Masterpiece Galleries',
        category: 'Culture',
        location: 'Pincian Hill',
        description: 'Bernini sculptures and Caravaggio canvases in climate-controlled grand salon.',
        cost: 20,
      },
    },
    {
      id: 'act-rom-03',
      title: 'Trastevere Sunset Food & Natural Wine Walk',
      category: 'Culinary',
      location: 'Trastevere',
      durationHours: 2.5,
      cost: 45,
      isOutdoor: false,
      isAnchorEvent: true,
      weatherSuitability: 'All-Weather',
      description: 'Sampling cacio e pepe, supplì, and artisanal gelato in atmospheric medieval alleys.',
    },
  ],
  Reykjavik: [
    {
      id: 'act-kef-01',
      title: 'Thingvellir National Park Fissure & Rift Valley Hike',
      category: 'Nature',
      location: 'Golden Circle',
      durationHours: 3.5,
      cost: 0,
      isOutdoor: true,
      isAnchorEvent: true,
      weatherSuitability: 'Sunny Preferred',
      description: 'Walking between North American and Eurasian tectonic plates in dramatic glacial landscapes.',
      rainAlternative: {
        title: 'Perlan Wonders of Iceland & Real Ice Cave Dome',
        category: 'Culture',
        location: 'Öskjuhlíð Hill',
        description: 'Indoor 100-meter man-made glacial ice tunnel, planetarium aurora show, and 360 observation deck.',
        cost: 32,
      },
    },
    {
      id: 'act-kef-02',
      title: 'Sky Lagoon Geothermal Oceanfront Pure Pass',
      category: 'Nature',
      location: 'Kársnes Harbour',
      durationHours: 2.5,
      cost: 72,
      isOutdoor: false,
      isAnchorEvent: true,
      weatherSuitability: 'All-Weather',
      description: 'Sublime geothermal infinity lagoon overlooking the North Atlantic Ocean with 7-step ritual.',
    },
  ],
};

export const DATASET_STATS = {
  flightsCount: 10,
  hotelsCount: 9,
  destinationsCount: 4,
  attractionsCount: 11,
  note: DATASET_DISCLAIMER,
};
