export const CURRENCY_MULTIPLIERS = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 152,
  SGD: 1.34,
  AUD: 1.52,
};

export const MCP_SERVERS_INFO = {
  flights: {
    serverId: '@gvzq/flight-mcp',
    name: 'Smithery Flight Pricing Engine',
    transport: 'streamable-mcp-http',
    verifiedVersion: '1.2.4',
    status: 'connected',
    latencyMs: 42,
  },
  hotels: {
    serverId: 'google/hotels',
    name: 'Google Hotels Live Availability',
    transport: 'streamable-mcp-http',
    verifiedVersion: '2.0.1',
    status: 'connected',
    latencyMs: 38,
  },
  weather: {
    serverId: 'rvibek/smthery',
    name: 'Smithery Weather Forecast & Rain Radar',
    transport: 'streamable-mcp-http',
    verifiedVersion: '0.9.8',
    status: 'connected',
    latencyMs: 29,
  },
  attractions: {
    serverId: 'exasearch/exa-mcp',
    name: 'Exa Semantic Attractions & Event Anchors',
    transport: 'streamable-mcp-http',
    verifiedVersion: '1.4.0',
    status: 'connected',
    latencyMs: 51,
  },
};

export const FLIGHT_CATALOG = {
  TYO: [
    {
      id: 'fl-hnd-101',
      airline: 'All Nippon Airways (ANA)',
      airlineCode: 'NH',
      flightNumber: 'NH 109',
      departureTime: '11:30 AM',
      arrivalTime: '03:15 PM (+1d)',
      duration: '14h 45m',
      stops: 'Nonstop',
      basePrice: 1120,
      cabinClass: 'Economy Standard',
      carbonKg: 490,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
    {
      id: 'fl-hnd-102',
      airline: 'Japan Airlines (JAL)',
      airlineCode: 'JL',
      flightNumber: 'JL 005',
      departureTime: '01:45 PM',
      arrivalTime: '05:30 PM (+1d)',
      duration: '14h 45m',
      stops: 'Nonstop',
      basePrice: 1240,
      cabinClass: 'Premium Economy',
      carbonKg: 510,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
    {
      id: 'fl-hnd-103',
      airline: 'United Airlines',
      airlineCode: 'UA',
      flightNumber: 'UA 79',
      departureTime: '09:10 AM',
      arrivalTime: '01:55 PM (+1d)',
      duration: '15h 45m',
      stops: '1 Stop',
      stopCity: 'SFO (1h 35m)',
      basePrice: 890,
      cabinClass: 'Economy Saver',
      carbonKg: 535,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
  ],
  PAR: [
    {
      id: 'fl-cdg-201',
      airline: 'Air France',
      airlineCode: 'AF',
      flightNumber: 'AF 023',
      departureTime: '04:30 PM',
      arrivalTime: '06:05 AM (+1d)',
      duration: '7h 35m',
      stops: 'Nonstop',
      basePrice: 740,
      cabinClass: 'Economy Classic',
      carbonKg: 280,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
    {
      id: 'fl-cdg-202',
      airline: 'Delta Air Lines',
      airlineCode: 'DL',
      flightNumber: 'DL 264',
      departureTime: '07:20 PM',
      arrivalTime: '08:55 AM (+1d)',
      duration: '7h 35m',
      stops: 'Nonstop',
      basePrice: 810,
      cabinClass: 'Comfort+',
      carbonKg: 290,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
    {
      id: 'fl-cdg-203',
      airline: 'British Airways',
      airlineCode: 'BA',
      flightNumber: 'BA 178',
      departureTime: '08:00 AM',
      arrivalTime: '09:20 PM',
      duration: '8h 20m',
      stops: '1 Stop',
      stopCity: 'LHR (1h 15m)',
      basePrice: 590,
      cabinClass: 'Standard Economy',
      carbonKg: 310,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
  ],
  ROM: [
    {
      id: 'fl-fco-301',
      airline: 'ITA Airways',
      airlineCode: 'AZ',
      flightNumber: 'AZ 609',
      departureTime: '05:40 PM',
      arrivalTime: '08:15 AM (+1d)',
      duration: '8h 35m',
      stops: 'Nonstop',
      basePrice: 860,
      cabinClass: 'Classic Economy',
      carbonKg: 330,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
    {
      id: 'fl-fco-302',
      airline: 'Lufthansa',
      airlineCode: 'LH',
      flightNumber: 'LH 401',
      departureTime: '03:50 PM',
      arrivalTime: '08:40 AM (+1d)',
      duration: '9h 50m',
      stops: '1 Stop',
      stopCity: 'MUC (1h 20m)',
      basePrice: 680,
      cabinClass: 'Economy Smart',
      carbonKg: 345,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
  ],
  KEF: [
    {
      id: 'fl-kef-401',
      airline: 'Icelandair',
      airlineCode: 'FI',
      flightNumber: 'FI 614',
      departureTime: '08:30 PM',
      arrivalTime: '06:15 AM (+1d)',
      duration: '5h 45m',
      stops: 'Nonstop',
      basePrice: 620,
      cabinClass: 'Economy Standard',
      carbonKg: 210,
      baggageIncluded: true,
      mcpServer: '@gvzq/flight-mcp',
    },
    {
      id: 'fl-kef-402',
      airline: 'Play Airlines',
      airlineCode: 'OG',
      flightNumber: 'OG 112',
      departureTime: '06:15 PM',
      arrivalTime: '04:30 AM (+1d)',
      duration: '6h 15m',
      stops: 'Nonstop',
      basePrice: 430,
      cabinClass: 'Basic Economy',
      carbonKg: 225,
      baggageIncluded: false,
      mcpServer: '@gvzq/flight-mcp',
    },
  ],
};

export const HOTEL_CATALOG = {
  Tokyo: [
    {
      id: 'ht-tko-01',
      name: 'The Capitol Hotel Tokyu',
      neighborhood: 'Chiyoda / Akasaka',
      rating: 4.8,
      reviews: 1420,
      basePrice: 380,
      amenities: ['Direct Subway Access', 'Japanese Garden View', 'Spa & Onsen', 'Free High-Speed Wi-Fi'],
      cancellation: 'Free cancellation up to 48 hours prior',
      mcpServer: 'google/hotels',
      badge: 'Staff Choice',
    },
    {
      id: 'ht-tko-02',
      name: 'Trunk Hotel Yoyogi Park',
      neighborhood: 'Shibuya / Harajuku',
      rating: 4.7,
      reviews: 890,
      basePrice: 290,
      amenities: ['Rooftop Infinity Pool', 'Boutique Coffee Lounge', 'Curated Art Decor', 'Locally Sourced Dining'],
      cancellation: 'Free cancellation up to 7 days prior',
      mcpServer: 'google/hotels',
      badge: 'Design Boutique',
    },
    {
      id: 'ht-tko-03',
      name: 'Hotel Gracery Shinjuku',
      neighborhood: 'Kabukicho / Shinjuku',
      rating: 4.5,
      reviews: 3250,
      basePrice: 165,
      amenities: ['Godzilla Terrace', '5 min from JR Shinjuku Station', 'Modern Minimalist', 'Concierge Service'],
      cancellation: 'Non-refundable discount rate available',
      mcpServer: 'google/hotels',
      badge: 'Best Value',
    },
  ],
  Paris: [
    {
      id: 'ht-par-01',
      name: 'Hôtel Madame Rêve',
      neighborhood: '1st Arrondissement (Louvre - Bourse)',
      rating: 4.8,
      reviews: 640,
      basePrice: 440,
      amenities: ['Panoramic Sky Bar', 'Historic Post Office Revival', 'Signature Spa', 'Luxury Robes & Linens'],
      cancellation: 'Free cancellation up to 72 hours prior',
      mcpServer: 'google/hotels',
      badge: 'Luxury Historic',
    },
    {
      id: 'ht-par-02',
      name: 'The Hoxton, Paris',
      neighborhood: '2nd Arrondissement (Sentier)',
      rating: 4.6,
      reviews: 1820,
      basePrice: 285,
      amenities: ['18th-century Courtyard', 'Rivié Brasserie', 'Speakeasy Cocktail Bar', 'Walk to Marais'],
      cancellation: 'Free cancellation up to 48 hours prior',
      mcpServer: 'google/hotels',
      badge: 'Social & Hip',
    },
  ],
  Rome: [
    {
      id: 'ht-rom-01',
      name: 'Singer Palace Hotel',
      neighborhood: 'Trevi / Pantheon',
      rating: 4.9,
      reviews: 790,
      basePrice: 420,
      amenities: ['Rooftop Jim’s Bar', 'Steps to Pantheon & Trevi', 'Art Deco Architecture', 'Full Butler Service'],
      cancellation: 'Free cancellation up to 48 hours prior',
      mcpServer: 'google/hotels',
      badge: 'Exceptional Luxury',
    },
    {
      id: 'ht-rom-02',
      name: 'The Hoxton Rome',
      neighborhood: 'Parioli / Villa Borghese',
      rating: 4.6,
      reviews: 1150,
      basePrice: 220,
      amenities: ['Mid-century Italian Design', 'Beverly Restaurant', 'Spacious Terrace', 'Boutique Coffee'],
      cancellation: 'Free cancellation up to 72 hours prior',
      mcpServer: 'google/hotels',
      badge: 'Boutique Relaxed',
    },
  ],
  Reykjavik: [
    {
      id: 'ht-kef-01',
      name: 'The Reykjavik EDITION',
      neighborhood: 'Old Harbour / Harpa',
      rating: 4.8,
      reviews: 910,
      basePrice: 490,
      amenities: ['Geothermal Spa with Hydrotherapy', 'Rooftop Northern Lights Lounge', 'Harbour Waterfront Views'],
      cancellation: 'Free cancellation up to 7 days prior',
      mcpServer: 'google/hotels',
      badge: 'Nordic Luxury',
    },
    {
      id: 'ht-kef-02',
      name: 'Exeter Hotel by Keahotels',
      neighborhood: 'Old Harbour Quarter',
      rating: 4.6,
      reviews: 1430,
      basePrice: 245,
      amenities: ['Nordic Sauna & Cold Plunge', 'Deig Bakery on-site', 'Industrial Contemporary', 'Port Access'],
      cancellation: 'Free cancellation up to 48 hours prior',
      mcpServer: 'google/hotels',
      badge: 'Harbour Chic',
    },
  ],
};

export const WEATHER_FORECASTS = {
  Tokyo: [
    { day: 1, tempC: 21, condition: 'Sunny & Crisp', rainChance: 10, isRainy: false },
    { day: 2, tempC: 19, condition: 'Passing Showers', rainChance: 68, isRainy: true },
    { day: 3, tempC: 22, condition: 'Clear Sky', rainChance: 15, isRainy: false },
    { day: 4, tempC: 20, condition: 'Partly Cloudy', rainChance: 25, isRainy: false },
  ],
  Paris: [
    { day: 1, tempC: 18, condition: 'Mild & Sunny', rainChance: 15, isRainy: false },
    { day: 2, tempC: 16, condition: 'Intermittent Rain', rainChance: 78, isRainy: true },
    { day: 3, tempC: 17, condition: 'Overcast with Drizzle', rainChance: 65, isRainy: true },
    { day: 4, tempC: 19, condition: 'Sunny Breaks', rainChance: 20, isRainy: false },
  ],
  Rome: [
    { day: 1, tempC: 24, condition: 'Warm & Sunny', rainChance: 5, isRainy: false },
    { day: 2, tempC: 23, condition: 'Clear', rainChance: 10, isRainy: false },
    { day: 3, tempC: 20, condition: 'Thunderstorms', rainChance: 82, isRainy: true },
    { day: 4, tempC: 22, condition: 'Breezy & Fair', rainChance: 20, isRainy: false },
  ],
  Reykjavik: [
    { day: 1, tempC: 8, condition: 'Cool & Clear (Aurora Alert)', rainChance: 12, isRainy: false },
    { day: 2, tempC: 6, condition: 'Sleet & Gusts', rainChance: 85, isRainy: true },
    { day: 3, tempC: 7, condition: 'Overcast & Crisp', rainChance: 30, isRainy: false },
    { day: 4, tempC: 9, condition: 'Scattered Showers', rainChance: 55, isRainy: true },
  ],
};

export const ATTRACTION_CATALOG = {
  Tokyo: [
    {
      title: 'Meiji Jingu Shrine & Yoyogi Forest Walk',
      category: 'Culture',
      isOutdoor: true,
      cost: 0,
      rainAlternative: {
        title: 'Mori Art Museum & Roppongi Hills Observation',
        category: 'Culture',
        location: 'Roppongi Hills Mori Tower 53F',
        description: 'World-renowned contemporary art with indoor 360-degree skyline views.',
        cost: 18,
      },
    },
    {
      title: 'Shinjuku Gyoen National Garden Walking Tour',
      category: 'Nature',
      isOutdoor: true,
      cost: 5,
      rainAlternative: {
        title: 'teamLab Borderless Digital Art Museum',
        category: 'Culture',
        location: 'Azabudai Hills',
        description: 'Spectacular covered immersive projection mapping and interactive digital installations.',
        cost: 28,
      },
    },
    {
      title: 'Tsukiji Outer Market Culinary Tasting Crawl',
      category: 'Culinary',
      isOutdoor: false,
      cost: 35,
    },
  ],
  Paris: [
    {
      title: 'Montmartre & Sacré-Cœur Hilltop Walking Exploration',
      category: 'Sightseeing',
      isOutdoor: true,
      cost: 0,
      rainAlternative: {
        title: 'Musée d’Orsay Impressionist Masterpieces Tour',
        category: 'Culture',
        location: 'Left Bank 7th Arr.',
        description: 'Covered Beaux-Arts former railway station exhibiting Monet, Renoir, and Van Gogh.',
        cost: 16,
      },
    },
    {
      title: 'Jardin du Luxembourg & Latin Quarter Bookstalls',
      category: 'Nature',
      isOutdoor: true,
      cost: 0,
      rainAlternative: {
        title: 'Historic Covered Passages Tour (Galerie Vivienne & Panoramas)',
        category: 'Culture',
        location: '2nd Arrondissement',
        description: 'Glass-roofed 19th-century mosaic arcades with antiquarian bookstores and tearooms.',
        cost: 0,
      },
    },
    {
      title: 'Seine River Sunset Architecture Cruise',
      category: 'Sightseeing',
      isOutdoor: false,
      cost: 22,
    },
  ],
  Rome: [
    {
      title: 'Colosseum & Roman Forum Archaeological Arena Walk',
      category: 'Culture',
      isOutdoor: true,
      cost: 26,
      rainAlternative: {
        title: 'Capitoline Museums & Underground Galleria Lapidaria',
        category: 'Culture',
        location: 'Piazza del Campidoglio',
        description: 'Ancient bronze and marble masterpieces in protected covered palazzi.',
        cost: 18,
      },
    },
    {
      title: 'Villa Borghese Gardens & Rowboat Lake',
      category: 'Nature',
      isOutdoor: true,
      cost: 6,
      rainAlternative: {
        title: 'Galleria Borghese Masterpiece Galleries',
        category: 'Culture',
        location: 'Pincian Hill',
        description: 'Bernini sculptures and Caravaggio canvases in climate-controlled grand salon.',
        cost: 20,
      },
    },
  ],
  Reykjavik: [
    {
      title: 'Thingvellir National Park Fissure & Rift Valley Hike',
      category: 'Nature',
      isOutdoor: true,
      cost: 0,
      rainAlternative: {
        title: 'Perlan Wonders of Iceland & Real Ice Cave Dome',
        category: 'Culture',
        location: 'Öskjuhlíð Hill',
        description: 'Indoor 100-meter man-made glacial ice tunnel, planetarium aurora show, and 360 observation deck.',
        cost: 32,
      },
    },
    {
      title: 'Sky Lagoon Geothermal Oceanfront Pure Pass',
      category: 'Nature',
      isOutdoor: false,
      cost: 72,
    },
  ],
};
